apiVersion: apps/v1
kind: Deployment

metadata:
  name: sre-go-web-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sre-go-web-app

  template:
    metadata:
      labels:
        app: sre-go-web-app

    spec:
      containers:
        - name: sre-go-web-app

          image: 724413958876.dkr.ecr.us-east-1.amazonaws.com/sre-go-web-app:1a0b022f878005324b37757fa142d642492a914e

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15